settings:
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 8081
  host: localhost
schema:
- name: mainnet
  path: .
  commands:
    vet:
      status: true
    fmt:
      status: true
    test:
      status: true
    generate:
      status: true
    install:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
